name: Pictures By Abbey
favicon: null
layout_spectrum: 0.99791
typography_spectrum: 0.85476
title: Pictures By Abbey
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#cad0dd'
    - '#401fe1'
    - '#9ba1b6'
    - '#845647'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
