name: Pictures By Abbey
favicon: null
layout_spectrum: 0.5321379292290658
typography_spectrum: 0.4977974444627762
title: Pictures By Abbey
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.2545884179417044
  lightness: 0.1717394965235144
  saturation: 0.5002521318383515
  rhythmicContrast: 0.44909946084953845
purpose: []
