name: Pictures By Abbey
favicon: null
layout_spectrum: 0.49165
typography_spectrum: 0.94063
title: Pictures By Abbey
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a9a6ad'
    - '#000000'
    - '#e0e0e2'
    - '#595764'
    - '#30c5d3'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
